name: Release Please
on:
  push:
    branches:
      - master

jobs:
  releasePlease:
    runs-on: ubuntu-latest
    steps:
      - id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          release-type: node
          package-name: release-please-action
